name: weatherapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  geolocator: ^9.0.2
  fluttertoast: ^8.2.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  dio: ^5.0.1
  flutter_weather_bg_null_safety:
    git:
      url: https://github.com/nizwar/flutter_weather_background.git
  intl: ^0.18.0
  glass: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/'
    - 'assets/images/'
